load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")
load("@build_bazel_rules_apple//apple:macos.bzl", "macos_application")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("//swift-shared:concurrency.bzl", "STRICT_MAINACTOR_COPTS")
load("//swift-shared:swift-ide.bzl", "ide")

swift_library(
    name = "lib",
    srcs = ["MainApp.swift"],
    copts = STRICT_MAINACTOR_COPTS,
    deps = [
        "//local-call-app/content",
    ],
)

filegroup(
    name = "AppIcon",
    srcs = glob(["Assets.xcassets/AppIcon.appiconset/*"]),
)

ios_application(
    name = "local-call-app",
    app_icons = [":AppIcon"],
    bundle_id = "com.ayroblu.local-call-app",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["Resources/Info.plist"],
    minimum_os_version = "18.0",
    provisioning_profile = select({
        # cp ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/<uuid>.mobileprovision .
        "//conditions:default": "development.mobileprovision",
        "@bazel-demo//:release_build": "distribution.mobileprovision",
    }),
    visibility = ["//visibility:public"],
    deps = [":lib"],
)

macos_application(
    name = "macos_app",
    bundle_id = "com.ayroblu.local-call-app.macos",
    bundle_name = "Local Call App",
    entitlements = "Resources/Mac.entitlements",
    infoplists = ["Resources/MacInfo.plist"],
    minimum_os_version = "14.0",
    visibility = ["//visibility:public"],
    deps = [":lib"],
)

sh_binary(
    name = "macos",
    srcs = ["run-macos.sh"],
    data = [":macos_app"],
)

ide(
    macos_xcode_targets = [":macos_app"],
    targets = ["//local-call-app"],
    xcode_project_name = "local-call-app",
    xcode_targets = [":local-call-app"],
)
