#!/bin/zsh
# Updates the Cargo.lock file
# cargo generate-lockfile
# Updates the definitions for rust analyzer
TARGET="${1:-//rust-code/...}"
bazel run @rules_rust//tools/rust_analyzer:gen_rust_project -- "$TARGET"
