load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("//swift-shared:concurrency.bzl", "STRICT_MAINACTOR_COPTS")
load("//swift-shared:swift-ide.bzl", "ide")

swift_library(
    name = "lib",
    srcs = ["BazelApp.swift"],
    copts = STRICT_MAINACTOR_COPTS,
    deps = [
        "//example-ios-app/JsWrap",
        "//example-ios-app/drag-example",
        "//example-ios-app/home",
        "//example-ios-app/jotai-example",
        "//example-ios-app/rust-logs",
        "//example-ios-app/rust-uniffi-example",
        "//example-ios-app/rust_lib/bridge",
        "//example-ios-app/sqlite-example",
        "//example-ios-app/utils",
        "//rust-code/client-shared/jotai-logs:jotai-logs-swift",
        "//rust-code/client-shared/jotai-logs/swift",
        "//swift-shared/FileUtils",
        "//swift-shared/SwiftUIUtils",
    ],
)

ios_application(
    name = "example-ios-app",
    bundle_id = "build.bazel.rules-apple-example",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["Resources/Info.plist"],
    linkopts = ["-lsqlite3"],
    minimum_os_version = "18.0",
    visibility = ["//visibility:public"],
    deps = [":lib"],
)

ide(
    targets = ["//example-ios-app"],
    xcode_project_name = "example-ios-app",
)
